# /.github/workflows/daily.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,20 * * *' # every day at 8am and 8pm
name: Download any new data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v3
        id: setup-java
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: curl -Ls https://sh.jbang.dev | bash -s - app setup && echo "/home/runner/.jbang/bin" >> $GITHUB_PATH && rm -f hook_post_*.sh
      - name: Fetch
        run: ./fetch.java
        env:
          JBANG_REPO: /home/runner/.jbang/repository
      - run: git add data
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
          BRANCH_NAME: 'main'
