# /.github/workflows/daily.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,20 * * *' # every day at 8am and 8pm
name: Download any new data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 11.0.11.hs-adpt
      - uses: sdkman/sdkman-action@master
        id: jbang
        with:
          candidate: jbang
          version: 0.79.0
      - uses: actions/setup-java@v1
        id: setup-java
        with:
          java-version: 11.0.11.hs-adpt
          jdkFile: ${{ steps.sdkman.outputs.file }}
      - name: Fetch
        run: fetch.java
#        env:
#          JBANG_REPO: /root/.jbang/repository
      - run: git add data
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
          BRANCH_NAME: 'main'
