# /.github/workflows/daily.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,20 * * *' # every day at 8am and 8pm
name: Download any new data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: ${{ runner.os }}-jbang-${{ hashFiles('*.java') }}
          restore-keys: |
            ${{ runner.os }}-jbang-
      - name: Fetch
        uses: jbangdev/jbang-action@v0.79.0
        with:
          script: fetch.java
        env:
          JBANG_REPO: /root/.jbang/repository
          FETCH_JSON: ${{ secrets.FETCH_JSON }}
      - run: git add data
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
          BRANCH_NAME: 'main'
