#   Copyright 2021 Stephen Connolly
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

name: Revision
on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stephenc/docker-science-data-reporting:v1.0.0
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Revision ${{ github.ref }}
          body: ''
          draft: true
          prerelease: false
      - name: Generate
        run: |
          make init
          make paper.zip
      - name: Upload Paper PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/main.pdf
          asset_name: paper.pdf
          asset_content_type: application/pdf
      - name: Upload Full paper ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: paper.zip
          asset_name: paper.zip
          asset_content_type: application/zip
